version: '3.8'

services:
  nestjs-otp:
    build: .
    container_name: otp-email-service
    restart: always
    ports:
      - "50500:3000"
    env_file:
      - .env
    volumes:
    - ./uploads:/app/uploads